spring:
  datasource:
    url: jdbc:mysql://localhost:3306/log?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false&allowMultiQueries=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

server:
  port: 882

owinfo:
  audit-log:
    enabled: true
    source: macao-flight
    tableName: t_apis_log
    enabledSpel: false
    database: SQLServer
    monthlySubTable: true
    datasource:
      host: 223.223.199.22
      port: 2221
      database: RiskH2000
      username: sa
      password: 1qaz!QAZ
